[build]
  base = "project"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://krishimitra-api.onrender.com"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
