[build]
  base = "project"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  MISE_CONFIG = '{ "idiomatic_version_file_enable_tools": ["node"] }'
  NEXT_PUBLIC_API_URL = "https://krishimitra-api.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
