[build]
  base = "project"
  command = "npm run build"
  publish = ".next"  # <== relative to `project/`, not `project/.next`

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://krishimitra-api.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
